# -*- coding: utf-8 -*-
"""ExamCaliforniaHousing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JNltJp43WTh8hpA-aPUAlySg7yC3F-4k
"""

#Import needed libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('housing.csv')
df

df_copy=df

df_copy.shape

df_copy.dtypes

df_copy.isnull().sum()

df_copy.dropna(inplace=True)

from sklearn.preprocessing import LabelEncoder

Le=LabelEncoder()
df_copy['ocean_proximity']=Le.fit_transform(df_copy['ocean_proximity'])
df_copy.dtypes

from sklearn.model_selection import train_test_split

X=df_copy.drop(['median_house_value'],axis=1)
y=df_copy['median_house_value']

X

y

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

train_data=X_test.join(y_test)
train_data

train_data.hist(figsize=(10,10))

train_data.corr()

plt.figure(figsize=(10,10))
sns.heatmap(train_data.corr(),annot=True)
plt.show()

plt.figure(figsize=(15,8))
sns.scatterplot(x='latitude',y='longitude',data=df_copy,hue='median_house_value')
plt.show()

from sklearn.linear_model import LinearRegression

lr=LinearRegression()

X_train=train_data.drop(['median_house_value'],axis=1)
y_train=train_data['median_house_value']

lr.fit(X_train,y_train)

lr.score(X_test,y_test)

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

X_train_s=scaler.fit_transform(X_train)
X_test_s=scaler.transform(X_test)

lr.fit(X_train_s,y_train)

lr.score(X_test_s,y_test)

from sklearn.ensemble import RandomForestRegressor
Rfr=RandomForestRegressor()

Rfr.fit(X_train,y_train)

Rfr.score(X_test,y_test)

Rfr.fit(X_train_s,y_train)

Rfr.score(X_test_s,y_test)

result=Rfr.predict(X_test_s)

comparision_df=pd.DataFrame({'Actual':y_test,'Predicted':result})
comparision_df

